server:
  port: 9000
  servlet:
    context-path: /booking

spring:
  application:
    name: booking-srv
  profiles:
    active: dev
  datasource:
    druid:
      name: ds
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 50
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379

session:
  #expire缓存key超时时间，-1持久化，-2和session时间一样，默认-2
  expire: -2
  key-prefix: booking:shiro:session
  #本地ThreadLocal超时时间
  sessionInMemoryTimeout: 1000
  # user的id
  principalIdFieldName: id
  #redis缓存超时时间,s
  cache-expire: 1800
  cache-key-prefix: booking:shiro:cache
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-locations: classpath*:mybatis/config.xml

shiro:
  login:
    #登录态过期时间：1天
    expiredtime: 86400000

booking:
  url: http://search.dangdang.com/
