server:
  port: 9000
  servlet:
    context-path: /booking

#shiro:
#  enabled: false
#  annotations:
#    enabled: false

spring:
#  aop:
#    auto: true
#    proxy-target-class: true
  application:
    name: booking-srv
  profiles:
    active: dev
  datasource:
    druid:
      name: ds
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 50
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-locations: classpath*:mybatis/config.xml

shiro:
  login:
    #登录态过期时间：2小时
    expiredtime: 7200000

booking:
  url: http://search.dangdang.com/
